### ISSUE TITLE
Failing CI on `main`

### ISSUE THREAD

**Issue by hadim** [conda-forge/fairseq-feedstock#30]
### Comment:

I have been re-building this package for pytorch 1.12 as well at https://github.com/conda-forge/fairseq-feedstock/pull/29

The CI in the PR were all green but once merged on `main` some osx arm64 ones had errors:

```
=x86_64-apple-darwin13.4.0
+host_alias=arm64-apple-darwin20.0.0
INFO: activate_clangxx_osx-arm64.sh made the following environmental changes:
+CLANGXX=arm64-apple-darwin20.0.0-clang++
+CXX=arm64-apple-darwin20.0.0-clang++
+CXXFLAGS=-ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -stdlib=libc++ -fvisibility-inlines-hidden -fmessage-length=0 -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/fairseq-0.12.3 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
+CXX_FOR_BUILD=$BUILD_PREFIX/bin/x86_64-apple-darwin13.4.0-clang++
+DEBUG_CXXFLAGS=-ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -stdlib=libc++ -fvisibility-inlines-hidden -fmessage-length=0 -Og -g -Wall -Wextra -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/fairseq-0.12.3 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
Setting up cross-python
find: fts_read: Invalid argument
Traceback (most recent call last):
  File "/Users/runner/miniforge3/bin/conda-mambabuild", line 10, in <module>
    sys.exit(main())
  File "/Users/runner/miniforge3/lib/python3.10/site-packages/boa/cli/mambabuild.py", line 256, in main
    call_conda_build(action, config)
  File "/Users/runner/miniforge3/lib/python3.10/site-packages/boa/cli/mambabuild.py", line 228, in call_conda_build
    result = api.build(
  File "/Users/runner/miniforge3/lib/python3.10/site-packages/conda_build/api.py", line 180, in build
    return build_tree(
  File "/Users/runner/miniforge3/lib/python3.10/site-packages/conda_build/build.py", line 3078, in build_tree
    packages_from_this = build(metadata, stats,
  File "/Users/runner/miniforge3/lib/python3.10/site-packages/conda_build/build.py", line 2198, in build
    utils.check_call_env(cmd, env=env, rewrite_stdout_env=rewrite_env,
  File "/Users/runner/miniforge3/lib/python3.10/site-packages/conda_build/utils.py", line 451, in check_call_env
    return _func_defaulting_env_to_os_environ("call", *popenargs, **kwargs)
  File "/Users/runner/miniforge3/lib/python3.10/site-packages/conda_build/utils.py", line 427, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/Users/runner/miniforge3/conda-bld/fairseq_1679934584320/work/conda_build.sh']' returned non-zero exit status 1.
```

I also had that error in the PR for only `py38 and osx-arm64` which I decided to disable (I thought it was an incompat error).

I am not sure from where this stochastic error is coming from since the PR CIs all passed.

Have you already seen that in the past @hmaarrfk with pytorch and osx-arm64?

**Comment by hadim** [comment]
Same error: after merging #31 on `main` where all the CIs are green, one CI is failing...

**Comment by hmaarrfk** [comment]
can likely close now.
